### ISSUE TITLE
关于jwt的自包含的问题

### ISSUE THREAD

**Issue by aizhimin** [wj596/jsets-shiro-spring-boot-starter#1]
如果在jwt中自包含了权限信息，是不是就不可控呢？

比如我管理员修改了这个用户的权限，怎么办？

另外退出登陆之后，修改密码之后，怎么处理？

**Comment by wj596** [comment]
jwt是一次性的，每次都会根据时间戳、访问主张等生成数据签名；1：修改了权限之后 下次访问又重新生成了，2：JWT是无状态鉴权，不存在退出的登陆的概念；

**Comment by wj596** [comment]
JWT适合的场景是：A系统询问B系统是否有权访问C系统，如果有权请开张票据，然后拿着这个票据去访问C系统，如果无权就直接拒绝了；

**Comment by aizhimin** [comment]
> 1：修改了权限之后 下次访问又重新生成了，2：JWT是无状态鉴权，不存在退出的登陆的概念；

管理员修改了权限，但是客户端并不知道。是不是客户端访问的时候发现没有权限之后，再主动去刷新？
