### ISSUE TITLE
还有后续的研发计划嘛？

### ISSUE THREAD

**Issue by imhuzi** [wj596/jsets-shiro-spring-boot-starter#2]
是否考虑集成 [buji-pac4j](https://github.com/bujiio/buji-pac4j)

**Comment by lzysuqianqiu** [comment]
怎么不再官方提供的spring boot集成商进行改造

**Comment by wj596** [comment]
做这个插件的时候还没有官方spring boot插件；

这个插件我们公司的所有项目都在用，后续会随着公司的需求更新；
