### ISSUE TITLE
关于CacheManager中放入ConcurrentHashedMap的问题

### ISSUE THREAD

**Issue by hequanb** [wj596/jsets-shiro-spring-boot-starter#4]
为什么要在这个地方放入一个关于Cache的map, 这样子放进去当不维护(不删除, 或者是我还不知道哪里有删除)的做法合适吗?
只是想简单提个问题, 希望你不要介意..

**Comment by wj596** [comment]
你是说缓存吗，使用Map作为缓存可以直接运行啊，方便。但是上线的项目一般会使用ehcache或redis
