### ISSUE TITLE
bean无法注入的错误

### ISSUE THREAD

**Issue by belial0317** [wj596/jsets-shiro-spring-boot-starter#5]
单独使用 jsets-shiro-spring-boot-starter的时候出现了这个错误：
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'shiroFilter' available
但jsets-shiro-demo的编译版可以运行成功
用代码构建的时候jsets-shiro-demo项目出现了以下错误：
Field jdbcEnhance in org.jsets.shiro.demo.service.UserService required a bean of type 'org.jsets.jdbc.JdbcEnhance' that could not be found.
请问是否还有 哪些配置和修改需要更新？

**Comment by belial0317** [comment]
正常了，我引入的shiro包冲突导致的

**Comment by wj596** [comment]
OK
